name: T-1
favicon: null
layout_spectrum: 0.3419563355855644
typography_spectrum: 0.4914316493086517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#b6b5b3'
    - '#695646'
    - '#2cd3b6'
  brandStrength: 0.75
  lightness: 0.6498222590889782
  saturation: 0.22031196882016957
  rhythmicContrast: 0.5
purpose: []
